name: "CD"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/ub-unibe-ch/cloud-azure-alz-devcontainer
          cacheFrom: ghcr.io/ub-unibe-ch/cloud-azure-alz-devcontainer
          imageTag: latest,${{ github.sha }}
          push: always
